### ISSUE TITLE
Determine best strategy for publicizing Food Drive on website

### ISSUE THREAD

**Issue by emilyriederer** [satRdays/chicago2020#9]
Our GCFD fundraising site is now live: https://chicago2020.satrdays.org/

I know the website is fairly cookie-cutter and hard to modify. We should discuss what options there are to make sure this is prominent on the page.

**Comment by angela-li** [comment]
Here's what I did so far @blallen22 @rsglazier:

1. Copied the callforpapers.html partial into a new file called donate.html in the partials folder
2. Created a new section called [params.donate] in the config.toml, copying the Call for Papers section.

It could be nice to include the logo of the Food Depository as well. This may need to be edited in the HTML of "donate.html" - see some of the other partials for how to store images...

**Comment by angela-li** [comment]
After I took the above steps, it still didn't show up, and I realized I needed a third step:

3. Copied [index.html ](https://github.com/satRdays/chicago2020/blob/master/layouts/index.html) from the SatRdays tempate and include a section for "Donate" - now included and in the right order!

**Comment by angela-li** [comment]
And now logo is added, in the "static/img/donate" folder + should be on the site! Last few commits got it done 🎉
